services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      #Para no poner credenciales sensibles docker compose lee automaticamente el archivo .env, allí se encuentran estas credenciales.
      POSTGRES_USER: ${POSTGRES_USER}
      # Password es la unica requerida para iniciar el contenedor de postgres, 
      #si no se especifica, el contenedor no se iniciará
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  backend: 
    build: 
      context: .
      dockerfile: docker/dockerfile.backend
      # "Contexto" es la ruta donde se encuentra el dockerfile y "dockerfile: ..." es la ruta donde está el dockerfile.backend.
    ports:
      - "3000:3000" 
      # 3000 es la convención mas no es obligatorio, se puede cambiar por cualquier otro puerto
    depends_on: 
      - postgres
      #depends_on dice que hasta que postgres no este listo, backend no se iniciará